version: '3.8'

services:
  api-dashboard:
    build: .
    container_name: api-dashboard
    ports:
      - "8000:8000"   # FastAPI backend
      - "8501:8501"   # Streamlit frontend
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for production caching
  # redis:
  #   image: redis:7-alpine
  #   container_name: api-dashboard-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes

# volumes:
#   redis_data:
